import os
import html as html_lib
from pathlib import Path
from collections import defaultdict

apps_dir = Path("src/apps")
previews_dir = Path("previews")
print(f"CWD: {os.getcwd()}, apps exists: {apps_dir.exists()}, files: {list(apps_dir.rglob('index.html'))}")

# Fallback emoji shown when an app has no generated preview (e.g. skipped apps).
CATEGORY_EMOJI = {
    "basic": "✨",
    "graphics": "🎨",
    "makelogo": "🔺",
    "math": "🧮",
    "serial": "🔌",
}
DEFAULT_EMOJI = "🧩"

entries = []
for index_file in sorted(apps_dir.rglob("index.html")):
    app_path = index_file.parent
    # e.g. "src/apps/makelogo/MakeabilityLabLogo"
    rel_path = str(app_path).replace("\\", "/")
    name = app_path.name  # e.g. "MakeabilityLabLogo"
    category = app_path.parent.name  # e.g. "makelogo"
    entries.append((category, name, rel_path))

# Group by category
by_category = defaultdict(list)
for category, name, path in entries:
    by_category[category].append((name, path))


def thumb_html(category, name):
    """Thumbnail markup for a card.

    Previews are generated by scripts/capture_previews.mjs into
    previews/<category>/<name>.webp (animated) and .poster.png (static).
    Cards degrade gracefully: animated WebP > static poster > category emoji.
    The poster doubles as the prefers-reduced-motion fallback (see CSS).
    """
    webp = previews_dir / category / f"{name}.webp"
    poster = previews_dir / category / f"{name}.poster.png"
    safe_name = html_lib.escape(name)

    if webp.exists():
        return (
            f'<img class="thumb-anim" src="{webp.as_posix()}" '
            f'alt="Animated preview of {safe_name}" loading="lazy" decoding="async">'
            f'<img class="thumb-poster" src="{poster.as_posix()}" '
            f'alt="Preview of {safe_name}" loading="lazy" decoding="async">'
        )
    if poster.exists():
        return (
            f'<img class="thumb-poster thumb-poster--only" src="{poster.as_posix()}" '
            f'alt="Preview of {safe_name}" loading="lazy" decoding="async">'
        )
    emoji = CATEGORY_EMOJI.get(category, DEFAULT_EMOJI)
    return f'<div class="thumb-emoji" aria-hidden="true">{emoji}</div>'


sections = ""
for category in sorted(by_category):
    cards = ""
    for name, path in by_category[category]:
        cards += f"""
        <a class="card" href="{path}/">
          <div class="card-thumb">{thumb_html(category, name)}</div>
          <div class="card-body">
            <div class="card-name">{html_lib.escape(name)}</div>
            <div class="card-category">{html_lib.escape(category)}</div>
          </div>
        </a>"""
    sections += f"<section><h2>{category}</h2><div class='grid'>{cards}</div></section>\n"

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <!-- This is an auto-generated file using GitHub Actions. Do not edit directly. -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Makeability Lab — JavaScript Demo Gallery</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 960px; margin: 0 auto; padding: 2rem; }}
    h1 {{ font-size: 1.8rem; margin-bottom: 0.25rem; }}
    h2 {{ font-size: 1.1rem; color: #555; border-bottom: 1px solid #ddd; padding-bottom: 0.25rem; }}
    .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 1rem; margin: 1rem 0 2rem; }}
    .card {{ display: block; border: 1px solid #ddd; border-radius: 8px; overflow: hidden; text-decoration: none; color: inherit; transition: box-shadow 0.15s, transform 0.15s; }}
    .card:hover {{ box-shadow: 0 4px 12px rgba(0,0,0,0.15); transform: translateY(-2px); }}
    .card:focus-visible {{ outline: 2px solid #1a73e8; outline-offset: 2px; }}
    .card-thumb {{ aspect-ratio: 360 / 224; background: #fafafa; display: flex; align-items: center; justify-content: center; border-bottom: 1px solid #eee; }}
    .card-thumb img {{ width: 100%; height: 100%; object-fit: cover; }}
    /* Keep all display rules at single-class specificity so the hide/show
       toggles below aren't overridden by `.card-thumb img`. */
    .thumb-anim {{ display: block; }}
    .thumb-poster {{ display: none; }}            /* shown only as the reduced-motion / no-anim fallback */
    .thumb-poster--only {{ display: block; }}      /* poster-only apps (e.g. serial) always show it */
    .thumb-emoji {{ font-size: 3.5rem; line-height: 1; }}
    .card-body {{ padding: 0.75rem 1rem 1rem; }}
    .card-name {{ font-weight: 600; font-size: 0.95rem; }}
    .card-category {{ font-size: 0.75rem; color: #888; margin-top: 0.25rem; }}

    /* Accessibility: honor reduced-motion by swapping the loop for the poster. */
    @media (prefers-reduced-motion: reduce) {{
      .thumb-anim {{ display: none; }}
      .thumb-poster {{ display: block; }}
    }}
  </style>
</head>
<body>
  <h1>Makeability Lab — JavaScript Demo Gallery</h1>
  {sections}
</body>
</html>"""

with open("index.html", "w") as f:
    f.write(html)

print(f"Generated gallery with {len(entries)} apps.")
